const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR'; // 展开侧边栏
const ADD_TAB = 'ADD_TAB'; // 添加标签页
const SET_LOCAL_DATA = 'SET_LOCAL_DATA'; // 扩充localData
const SET_TAB_ACTIVE_NAME = 'SET_TAB_ACTIVE_NAME'; // tab的activeName
const SET_ALERT_OPTION = 'SET_ALERT_OPTION';
const SET_RELOAD = 'SET_RELOAD';

export default {
  EXPAND_SIDEBAR,
  ADD_TAB,
  SET_LOCAL_DATA,
  SET_TAB_ACTIVE_NAME,
  SET_ALERT_OPTION,
  SET_RELOAD
}
